Django_web_store_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import ProfileCreateView, HelloView, ProfileView, StoreMainView, CartView, ProductDetailView, SignUp, \
    CheckoutView, CategoryDetailView, SubcategoryDetailView, CommentCreateView, CommentUpdateView, CommentDeleteView, \
    CommentProductDeleteView, CommentProductUpdateView, UserPasswordChangeView, UserDeleteView, OrderDetailView

urlpatterns = [
    # path('', views.store, name='store'),
    path('', StoreMainView.as_view(), name='store'),
    # path('hello/', HelloView.as_view()),
    # path('cart/', views.cart, name='cart'),
    path('cart/', CartView.as_view(), name='cart'),
    # path('products/', views.products_list_view, name='products_list'),
    # path('products/<int:id>/', views.products_detail, name='products_detail'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='products_detail'),
    # path('categories/', views.categories_list_view, name='categories_list'),
    # path('categories/<int:id>/', views.categories_detail_view, name='categories_detail_list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='categories_detail_list'),
    # path('subcategories/', views.subcategories_list_view, name='subcategories_list'),
    # path('subcategories/<int:id>/', views.subcategories_detail_view, name='subcategories_detail_list'),
    path('subcategories/<int:pk>/', SubcategoryDetailView.as_view(), name='subcategories_detail_list'),
    # path('checkout/', views.checkout, name='checkout'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    # path('sign-up/', views.sign_up_view, name='sign_up'),
    path('sign-up/', SignUp.as_view(), name='sign_up'),
    # path('profile/', views.profile_view, name='profile'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/create/', ProfileCreateView.as_view(), name='profile_create'),
    path('comment/<int:pk>/add/', CommentCreateView.as_view(), name='add_comment'),
    path('update_item/', views.updateItem, name='update_item'),
    path('comment/<int:pk>/edit/', CommentUpdateView.as_view(), name='edit_comment'),
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='delete_comment'),
    path('comment_product/<int:pk>/edit/', CommentProductUpdateView.as_view(), name='edit_product_comment'),
    path('comment_product/<int:pk>/delete/', CommentProductDeleteView.as_view(), name='delete_product_comment'),
    # path('profile/update/', UserUpdateProfileView.as_view(), name='update_profile'),
    path('profile/update/', views.user_update_profile, name='update_profile'),
    path('profile/user/update/', views.user_update, name='update_user'),
    # path('password', auth_views.PasswordChangeView.as_view()),
    path('profile/password/', UserPasswordChangeView.as_view(), name='change_password'),
    path('profile/delete/<int:pk>/', UserDeleteView.as_view(), name='delete_user'),
    # path('search/', SearchStoreList.as_view(), name='search'),
    path('search/', views.search_product, name='search'),
    path('profile/order/<int:pk>/', OrderDetailView.as_view(), name='order_detail_list'),
]

store/models.py
import os
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.db import models


# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField('auth.user', on_delete=models.CASCADE)
    street = models.CharField(max_length=50)
    number = models.CharField(max_length=15)
    post_code = models.CharField(max_length=6)
    city = models.CharField(max_length=25)
    phone_number = models.DecimalField(decimal_places=0, max_digits=9)
    info = models.TextField(blank=True)

    class Meta:
        verbose_name = "Profil"
        verbose_name_plural = "Profile"

    def __str__(self):
        return f"{self.user}, {self.info}"


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = "Kategoria"
        verbose_name_plural = "Kategorie"


class Subcategory(models.Model):
    name = models.CharField(max_length=50)
    category = models.ForeignKey('store.Category', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.category}/{self.name}"

    class Meta:
        verbose_name = "Podkategoria"
        verbose_name_plural = "Podkategorie"


def tb_media_path(instance, filename):
    file_extension = filename[(filename.rfind(".", -5, -1))::1]
    return os.path.join("tb", "%s%s" % (instance.name, file_extension)).lower()


class Product(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    thumbnail = models.ImageField(upload_to=tb_media_path, blank=True, default='placeholder/placeholder.png')
    subcategory = models.ForeignKey('Subcategory', on_delete=models.PROTECT)
    price = models.DecimalField(decimal_places=2, max_digits=7)

    def __str__(self):
        return f"{self.name}, {self.subcategory}"

    @property
    def get_total_score(self):
        commentset = self.comments.all()
        if len(commentset) == 0:
            return 0
        else:
            total = sum([comment.score for comment in commentset])//len(commentset)
        return total

    class Meta:
        verbose_name = "Produkt"
        verbose_name_plural = "Produkty"


def validate_score(value):
    if value <= 0 or value > 5:
        raise ValidationError(
            _('%(value) must be between 1 and 5'),
            params={'value': value}
        )

class Comment(models.Model):
    # creator = models.ForeignKey('Profile', related_name="profile_comments", null=True, on_delete=models.SET_NULL)
    creator = models.ForeignKey('auth.user', related_name="profile_comments", null=True, on_delete=models.SET_NULL)
    product = models.ForeignKey('Product', related_name="comments", on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    creation_datetime = models.DateTimeField(auto_now_add=True)
    comment = models.TextField()
    score = models.IntegerField(validators=[validate_score])

    def __str__(self):
        return f'{self.title} {self.comment} {self.creator} {self.score}'

    class Meta:
        verbose_name = "Komentarz"
        verbose_name_plural = "Komentarze"


class Order(models.Model):
    user = models.ForeignKey('auth.user', related_name='orders', on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.pk)

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

store/views.py
from django.contrib.auth.forms import AuthenticationForm, UsernameField, PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.base import TemplateResponseMixin, ContextMixin, View
from django.contrib.auth import login, logout, authenticate
from store.models import Profile, Category, Product, Subcategory, Comment, OrderItem, Order
from django.contrib.auth.models import User
from store.forms import CreateUserProfileForm, RegisterUserForm, CreateCommentForm, ProfileUpdateForm, UserUpdateForm
from django.views.generic import CreateView, TemplateView, DetailView, UpdateView, DeleteView, ListView
from django.urls import reverse_lazy, reverse
from django.http import JsonResponse
from django.db.models import Q
import json


class BaseStoreView(TemplateView):
    template_name = "store/base.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.user.is_authenticated:
            user = self.request.user
            order, created = Order.objects.get_or_create(user=user, complete=False)
            items = order.orderitem_set.all()
            cartItems = order.get_cart_items
        else:
            items = []
            order = {'get_cart_total': 0, 'get_cart_items': 0}
            cartItems = order['get_cart_items']

        context['categories'] = Category.objects.all()
        context['items'] = items
        context['order'] = order
        context['cartItems'] = cartItems

        return context

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['categories'] = Category.objects.all()
    #     return context


class BaseDetailView(DetailView):
    template_name = "store/base.html"

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['categories'] = Category.objects.all()
    #     return context

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.user.is_authenticated:
            user = self.request.user
            order, created = Order.objects.get_or_create(user=user, complete=False)
            items = order.orderitem_set.all()
            cartItems = order.get_cart_items
        else:
            items = []
            order = {'get_cart_total': 0, 'get_cart_items': 0}
            cartItems = order['get_cart_items']

        context['categories'] = Category.objects.all()
        context['items'] = items
        context['order'] = order
        context['cartItems'] = cartItems

        return context


class BaseCreateView(CreateView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.user.is_authenticated:
            user = self.request.user
            order, created = Order.objects.get_or_create(user=user, complete=False)
            items = order.orderitem_set.all()
            cartItems = order.get_cart_items
        else:
            items = []
            order = {'get_cart_total': 0, 'get_cart_items': 0}
            cartItems = order['get_cart_items']

        context['categories'] = Category.objects.all()
        context['items'] = items
        context['order'] = order
        context['cartItems'] = cartItems
        return context


class StoreMainView(BaseStoreView):
    template_name = 'store/store.html'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['products'] = Product.objects.all()
    #     return context

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.user.is_authenticated:
            user = self.request.user
            order, created = Order.objects.get_or_create(user=user, complete=False)
            items = order.orderitem_set.all()
            cartItems = order.get_cart_items
        else:
            items = []
            order = {'get_cart_total': 0, 'get_cart_items': 0}
            cartItems = order['get_cart_items']

        context['products'] = Product.objects.all()
        context['items'] = items
        context['order'] = order
        context['cartItems'] = cartItems

        return context

# def store(request):
#     products = Product.objects.all()
#     ctx = {'products': products}
#     return render(request, 'store/store.html', ctx)


class CartView(BaseStoreView):
    template_name = 'store/cart.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.user.is_authenticated:
            user = self.request.user
            order, created = Order.objects.get_or_create(user=user, complete=False)
            items = order.orderitem_set.all()
            cartItems = order.get_cart_items
        else:
            items = []
            order = {'get_cart_total': 0, 'get_cart_items': 0}
            cartItems = order['get_cart_items']

        context['items'] = items
        context['order'] = order
        context['cartItems'] = cartItems

        return context


class CheckoutView(BaseStoreView):
    template_name = 'store/checkout.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.user.is_authenticated:
            user = self.request.user
            order, created = Order.objects.get_or_create(user=user, complete=False)
            items = order.orderitem_set.all()
        else:
            items = []
            order = {'get_cart_total': 0, 'get_cart_items': 0}

        context['items'] = items
        context['order'] = order

        return context


def updateItem(request):
    # data = json.loads(request.data)
    data = json.loads(request.body.decode("utf-8"))
    productId = data['productId']
    action = data['action']

    print('action:', action)
    print('productId:', productId)

    user = request.user
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(user=user, complete=False)

    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity +1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity -1)

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('Produkt dodany do koszyka!', safe=False)


# def cart(request):
#     context = {}
#     return render(request, 'store/cart.html', context)


# def products_list_view(request):
#     products = Product.objects.all()
#     ctx = {'products': products}
#     return render(request, 'store/products_list_1.html', ctx)

class ProductDetailView(BaseDetailView):
    template_name = "store/product_detail.html"
    model = Product


# class ProductDetailView(BaseStoreView):
#     template_name = "store/product_detail.html"
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         try:
#             product = Product.objects.get(pk=kwargs['pk'])
#         except Product.DoesNotExist:
#             raise Http404("Product does not exist")
#
#         context['product'] = product
#         return context

# def products_detail(request, id):
#     product = get_object_or_404(Product, id=id)
#     ctx = {'product': product}
#     return render(request, 'store/products_detail.html', ctx)


# def categories_list_view(request):
#     #categories = Category.objects.all()
#     #ctx = {'categories': categories}
#     pass

class CategoryDetailView(BaseStoreView):
    template_name = "store/store.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = Product.objects.filter(subcategory__category=kwargs['pk'])
        return context


class SubcategoryDetailView(BaseStoreView):
    template_name = "store/store.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = Product.objects.filter(subcategory_id=kwargs['pk'])
        return context


class SignUp(BaseCreateView):
    form_class = RegisterUserForm
    success_url = reverse_lazy('store')
    template_name = 'registration/sign_up.html'


# def sign_up_view(request):
#     if request.method == 'POST':
#         form = RegisterUserForm(request.POST)
#         if form.is_valid():
#             user = form.save()
#             login(request, user)
#             return redirect('store')
#
#     else:
#         form = RegisterUserForm()
#
#     return render(request, 'registration/sign_up.html', {'form': form})

# def profile_view(request):
#     # profile = get_object_or_404(Profile, user_id=request.user.pk)
#     try:
#         profile = Profile.objects.get(user_id=request.user.pk)
#     except Profile.DoesNotExist:
#         return redirect('profile_create')
#     context = {'profile': profile}
#     return render(request, 'store/profile.html', context)


class HelloView(BaseStoreView):
    template_name = "store/hello.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['name'] = "John"
        return context


class ProfileView(BaseStoreView):
    template_name = "store/profile.html"

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     # try:
    #     #     profile = Profile.objects.get(user_id=self.request.user.pk)
    #     #
    #     # except Profile.DoesNotExist:
    #     #     return redirect('profile_create')
    #

store/templates/store/base.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
    <title> {% block title %} Django_web_store {% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

	<script type="text/javascript">
		var user = '{{request.user}}'

		function getToken(name) {
			var cookieValue = null;
			if (document.cookie && document.cookie !== '') {
				var cookies = document.cookie.split(';');
				for (var i = 0; i < cookies.length; i++) {
					var cookie = cookies[i].trim();

					// Does this cookie string begin with the name we want?
					if (cookie.substring(0, name.length + 1) === (name + '=')) {
						cookieValue = decodeURIComponent(cookie.substring(name.length + 1));

						break;
					}
				}
			}

			return cookieValue;
		}
		var csrftoken = getToken('csrftoken');

	</script>

</head>

<body>
	<div id="page-container">
		<div id="content-wrap" class="content-wrap" >
        	<nav class="navbar navbar-expand-lg navbar-dark bg-dark" STYLE="padding-top: 8px;">

				<div class="container-fluid navi"><button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
		  		</button>
					<div>
						<div class="" style="display: inline; float: left;">
		  					<a class="user-link" href="{% url 'store' %}" style="padding-right: 10px;">Django_web_store_SDA</a>
						</div>
						<div class="" style="display: inline; float: left; border: solid black 0px;">
    						<form class="d-flex" method="POST" action="{% url 'search' %}" style="">
									{% csrf_token %}
      							<input class="form-control me-2" type="search" placeholder="Szukaj..." name="searched"  aria-label="Search" style="width: 380px;">
      							<button class="btn btn-success" type="submit">Szukaj</button>
    						</form>
						</div>
					</div>

			  		<div class="form-block my-0 my-lg-0" style="min-width: 120px; float: right; display: inline;">
						{% if user.is_authenticated %}
				  		<div class="" style="min-width: 110px; display: inline; float: left;">
				    		<div class="welcome-msg" style="min-width: 90px; float: left;">Witaj
								<a class="user-link" href="{% url 'profile' %}">{{ user.username }}</a> !
				    		</div>
				    		<div style="width: 70px; float: right; border: solid black 0px;">
								<a href="{% url 'logout' %}" class="btn btn-warning">Logout</a>
				    		</div>
				  		</div>

        				{% else %}
				  		<div style="min-width: 70px; float: left;">

				  			<div style="width: 60px; float: middle;">
								<a href="{% url 'login' %}" class="btn btn-warning">Login</a>
				  			</div>
				  		</div>

						{% endif %}
						<div class="form-inline my-0 my-lg-0" style="width: 60px; display: block-inline; float: right;">
	     					<a href="{% url 'cart' %}">
	    					<img  id="cart-icon" src="{% static 'images/cart.png' %}">
	    					</a>
	    					<p id="cart-total">{{cartItems}}</p>
						</div>
			  		</div>
				</div><div style="clear: both; padding-left: 10px;">
		  		<div class="collapse navbar-collapse" id="navbarSupportedContent">

					<ul class="navbar-nav mr-auto">
			  			<li class="nav-item active">
							<a class="nav-link" href="{% url 'store' %}"> Strona główna <span class="sr-only"></span></a>
			  			</li>
			  				{% for category in categories %}
			  			<li class="nav-item dropdown">
				  			<a class="nav-link dropdown-toggle" href="{% url 'categories_detail_list' category.id %}" id="navbarDropdown">
					  		{{category.name}}<span class="sr-only"></span></a>
				  			<ul class="dropdown-menu">
				  			{% for subcategory in category.subcategory_set.all %}
				  				<li><a class="dropdown-item" href="{% url 'subcategories_detail_list' subcategory.id %}">
						   			{{ subcategory.name }} ({{ subcategory.product_set.count }})<span class="sr-only">(current)</span></a></li>

                			{% endfor %}
				  			</ul>
			  			</li>
			  				{% endfor %}
					</ul>
				</div>
<!--		  </div>-->
<!--			  <div class="form-block my-0 my-lg-0" style="min-width: 120px; display: inline; float: right; border: solid black 1px;">-->
<!--				{% if user.is_authenticated %}-->
<!--				  <div class="" style="min-width: 110px; display: inline; float: left;">-->
<!--				    <div class="welcome-msg" style="min-width: 90px; float: left;">Witaj-->
<!--						<a class="user-link" href="{% url 'profile' %}">{{ user.username }}</a> !-->
<!--				    </div>-->
<!--				    <div style="width: 70px; float: right; border: solid black 0px;">-->
<!--						<a href="{% url 'logout' %}" class="btn btn-warning">Logout</a>-->
<!--				    </div>-->
<!--				  </div>-->

<!--        		{% else %}-->
<!--				  <div style="min-width: 70px; float: left; border: solid black 0px;">-->

<!--				  <div style="width: 60px;  float: middle; border: solid black 0px;">-->
<!--						<a href="{% url 'login' %}" class="btn btn-warning">Login</a>-->
<!--				  </div>-->
<!--				  </div>-->

<!--				{% endif %}-->
<!--					<div class="form-inline my-0 my-lg-0" style="width: 60px; display: block-inline; float: right; border: solid black 0px;">-->
<!--	     				<a href="{% url 'cart' %}">-->
<!--	    				<img  id="cart-icon" src="{% static 'images/cart.png' %}">-->
<!--	    				</a>-->
<!--	    				<p id="cart-total">{{cartItems}}</p>-->
<!--					</div>-->
<!--			  </div>-->
<!--			  <div class="form-inline" style="position: absolute; top: 30; border: solid black 0px;" >-->
<!--    					<form method="POST" action="{% url 'search' %}" style="max-width:300px border: solid black 3px; float: left;">-->
<!--							{% csrf_token %}-->
<!--        					<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">-->
<!--        					<input type="search" placeholder="Szukaj..." name="searched">-->
<!--        					<button title="Search"><i class="fa fa-search">Szukaj</i></button>-->
<!--   					 	</form>-->
<!--					</div>-->

<!--			<div class="d-flex" style="position: relative; border: solid black 1px; padding-top: 4px; padding-right: 9px; margin-right:7px;" >-->
<!--    					<form method="POST" action="{% url 'search' %}" style="width: 400px; border: solid black 1px; float: left;">-->
<!--							{% csrf_token %}-->

<!--        					<input class="form-control me-2" type="search" placeholder="Szukaj..." name="searched" style="width:300px; position: inline;">-->
<!--        					<button class="btn btn-success" title="Search">Szukaj</button>-->
<!--   					 	</form>-->
<!--				</div>-->
<!--			<div class="container-fluid">-->
<!--    			<form class="d-flex" method="POST" action="{% url 'search' %}">-->
<!--							{% csrf_token %}-->
<!--      				<input class="form-control me-2" type="search" placeholder="Szukaj..." name="searched"  aria-label="Search">-->
<!--      				<button class="btn btn-success" type="submit">Szukaj</button>-->
<!--    			</form>-->
<!--			</div>-->
			</div>
		</nav>
		<hr>
		<main>

    		<div class="container">
				{% block content %}

        		{% endblock content %}

   			</div>

				{% block orders %}

				{% endblock orders %}

				{% block comment %}

				{% endblock comment %}


		</main>
<div>
		<footer class="text-muted py-5">
  			<div class="container">
    			<p class="float-end mb-1">
    	  			<a href="#">Back to top</a>
    			</p>
    			<p class="mb-1">2023 &copy; SDA grupa ZDPYTpol58!</p>

  			</div>
		</footer>
	</div>

	</div>

</div>

	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

	<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
</body>

</html>

store/templates/store/cart.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}
	<div class="row">
		<div class="col-lg-12">
			<div class="box-element">
				<a class="btn btn-outline-dark" href="{% url 'store' %}">&#x2190; Continue Shopping</a>
<br>
				<br>
				<table class="table">
					<tr>
						<th><h5>Items: <strong>{{order.get_cart_items}}</strong></h5></th>
						<th><h5>Total:<strong> {{order.get_cart_total}} PLN </strong></h5></th>
						<th>
							<a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'checkout' %}">Checkout</a>
						</th>
					</tr>
				</table>

			</div>

			<br>
			<div class="box-element">
				<div class="cart-row">
					<div style="flex:2"></div>
					<div style="flex:2"><strong>Item</strong></div>
					<div style="flex:1"><strong>Price</strong></div>
					<div style="flex:1"><strong>Quantity</strong></div>
					<div style="flex:1"><strong>Total</strong></div>
				</div>

				{% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.thumbnail.url}}"></div>
					<div style="flex:2"><p>{{item.product.name}}</p></div>
					<div style="flex:1"><p>{{item.product.price}}</p></div>
					<div style="flex:1">
						<p class="quantity">{{item.quantity}}</p>
						<div class="quantity">
							<img data-product={{item.product.id}} data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">

							<img data-product={{item.product.id}} data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
						</div>
					</div>
					<div style="flex:1"><p>{{item.get_total}}</p></div>
				</div>
				{% endfor %}
			</div>


			</div>
		</div>
	</div>
{% endblock content %}

store/templates/store/form.html
<div>
    <form method="post">
    {% csrf_token %}

        <table>{{ form }}</table>

    <input type="submit" value="Zatwierdź" class="btn btn-success">
  </form>
</div>

store/templates/store/products_detail.html
{% extends 'store/base.html' %}
{% load static %}

{% block content %}

    <div>
        <img class="thumbnail" src="{{ product.thumbnail.url }}">
            <div class="box-element product">
                <br>
                <h1><strong> {{product.name}} </strong></h1>
                <br>
                <h3>{{product.description}}</h3>
                <hr>
                <button class="btn btn-outline-secondary add-btn">Add to Cart</button>
                <h4 style="display: inline-block;float: right">{{product.price}}</h4>
                <hr>
                <a class="btn btn-outline-success" href="{% url 'store' %}">Back to Main</a>
            </div>
    </div>

{% endblock content %}